esphome:
  name: esphome-web-212cc8
  friendly_name: ESPHome Web 212cc8
  min_version: 2025.5.0
  name_add_mac_suffix: false

esp32:
  board: esp32dev
  framework:
    type: arduino

# Enable logging
logger:

# Enable Home Assistant API
api:

# Allow Over-The-Air updates
ota:
- platform: esphome

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password

captive_portal:
  
output:
  - platform: ledc
    pin: GPIO13
    id: gpio_13

# LED Light
light:
  - platform: monochromatic
    output: gpio_13
    name: "LEDka"

# Sensor of tempareture & humidity + I2C converter
i2c:
  - sda: GPIO21
    scl: GPIO22
    scan: true # Užitečné pro ladění, jestli se senzor detekuje

sensor:
  - platform: am2320
    temperature:
      name: "Byt 3+1 teplota"
    humidity:
      name: "Byt 3+1 vlhkost"
    update_interval: 60s
  - platform: adc
    pin: GPIO36
    name: "Vlkost pudy"
    id: moisture1
    accuracy_decimals: 4
    update_interval: 1s
    unit_of_measurement: "%"
    device_class: humidity
    icon: "mdi:water-percent"
    filters:
      - lambda: |-
          float moisture_dry_soil_value= 0.61328;
          float moisture_wet_soil_value =  0.25488;
          if (x >  moisture_dry_soil_value ) {
            return 0;
          } else if (x < moisture_wet_soil_value) {
            return 100;
          } else {
            return (moisture_dry_soil_value - x) / (moisture_dry_soil_value - moisture_wet_soil_value ) * 100.0;
          }

# Sensor of Capacitive Soil Moisture v1.2.

#updates above template to HA #
interval:
  - interval: 10sec
    then:
      - component.update: moisture1